// TODO - Dynamic load those files - require only works at build time
export function initMusic() {
    const music = [
        require('./assets/music/001.mp3'),
        require('./assets/music/002.mp3'),
        // require('./assets/music/003.mp3'),
        // require('./assets/music/004.mp3'),
        // require('./assets/music/005.mp3'),
        // require('./assets/music/006.mp3'),
        // require('./assets/music/007.mp3'),
        // require('./assets/music/008.mp3'),
        // require('./assets/music/009.mp3'),
        // require('./assets/music/010.mp3'),
        // require('./assets/music/011.mp3'),
        // require('./assets/music/012.mp3'),
        // require('./assets/music/013.mp3'),
        // require('./assets/music/014.mp3'),
        // require('./assets/music/015.mp3'),
        // require('./assets/music/016.mp3'),
        // require('./assets/music/017.mp3'),
        // require('./assets/music/018.mp3'),
        // require('./assets/music/019.mp3'),
        // require('./assets/music/020.mp3'),
        // require('./assets/music/021.mp3'),
        // require('./assets/music/022.mp3'),
        // require('./assets/music/023.mp3'),
        // require('./assets/music/024.mp3'),
        // require('./assets/music/025.mp3'),
        // require('./assets/music/026.mp3'),
        // require('./assets/music/027.mp3'),
        // require('./assets/music/028.mp3'),
        // require('./assets/music/029.mp3'),
        // require('./assets/music/030.mp3'),
        // require('./assets/music/031.mp3'),
        // require('./assets/music/032.mp3'),
        // require('./assets/music/033.mp3'),
        // require('./assets/music/034.mp3'),
        // require('./assets/music/035.mp3'),
        // require('./assets/music/036.mp3'),
        // require('./assets/music/037.mp3'),
        // require('./assets/music/038.mp3'),
        // require('./assets/music/039.mp3'),
        // require('./assets/music/040.mp3'),
        // require('./assets/music/041.mp3'),


    ];

    return music;
}

export function initSound() {
    const sound = [
        require('./assets/sounds/001.mp3'),
        require('./assets/sounds/002.mp3'),
        require('./assets/sounds/003.mp3'),
        require('./assets/sounds/004.mp3'),
        require('./assets/sounds/005.mp3'),
        require('./assets/sounds/006.mp3'),
        require('./assets/sounds/007.mp3'),
        require('./assets/sounds/008.mp3'),
        require('./assets/sounds/009.mp3'),
        require('./assets/sounds/010.mp3'),
        require('./assets/sounds/011.mp3'),
        require('./assets/sounds/012.mp3'),
        require('./assets/sounds/013.mp3'),
        require('./assets/sounds/014.mp3'),
        require('./assets/sounds/015.mp3'),
        require('./assets/sounds/016.mp3'),
        require('./assets/sounds/017.mp3'),
        require('./assets/sounds/018.mp3'),
        require('./assets/sounds/019.mp3'),
        require('./assets/sounds/020.mp3'),
        require('./assets/sounds/021.mp3'),
        require('./assets/sounds/022.mp3'),
        require('./assets/sounds/023.mp3'),
        require('./assets/sounds/024.mp3'),
        require('./assets/sounds/025.mp3'),
        require('./assets/sounds/026.mp3'),
        require('./assets/sounds/027.mp3'),
        require('./assets/sounds/028.mp3'),
        require('./assets/sounds/029.mp3'),
        require('./assets/sounds/030.mp3'),
        require('./assets/sounds/031.mp3'),
        require('./assets/sounds/032.mp3'),
        require('./assets/sounds/033.mp3'),
        require('./assets/sounds/034.mp3'),
        require('./assets/sounds/035.mp3'),
        require('./assets/sounds/036.mp3'),
        require('./assets/sounds/037.mp3'),
        require('./assets/sounds/038.mp3'),
        require('./assets/sounds/039.mp3'),
        require('./assets/sounds/040.mp3'),
        require('./assets/sounds/041.mp3'),
        require('./assets/sounds/042.mp3'),
        require('./assets/sounds/043.mp3'),
        require('./assets/sounds/044.mp3'),
        require('./assets/sounds/045.mp3'),
        require('./assets/sounds/046.mp3'),
        require('./assets/sounds/047.mp3'),
        require('./assets/sounds/048.mp3'),
        require('./assets/sounds/049.mp3'),
        require('./assets/sounds/050.mp3'),
        require('./assets/sounds/051.mp3'),
        require('./assets/sounds/052.mp3'),
        require('./assets/sounds/053.mp3'),
        require('./assets/sounds/054.mp3'),
        require('./assets/sounds/055.mp3'),
        require('./assets/sounds/056.mp3'),
        require('./assets/sounds/057.mp3'),
        require('./assets/sounds/058.mp3'),
        require('./assets/sounds/059.mp3'),
        require('./assets/sounds/060.mp3'),
        require('./assets/sounds/061.mp3'),
        require('./assets/sounds/062.mp3'),
        require('./assets/sounds/063.mp3'),
        require('./assets/sounds/064.mp3'),
        require('./assets/sounds/065.mp3'),
        require('./assets/sounds/066.mp3'),
        require('./assets/sounds/067.mp3'),
        require('./assets/sounds/068.mp3'),
        require('./assets/sounds/069.mp3'),
        require('./assets/sounds/070.mp3'),
        require('./assets/sounds/071.mp3'),
        require('./assets/sounds/072.mp3'),
        require('./assets/sounds/073.mp3'),
        require('./assets/sounds/074.mp3'),
        require('./assets/sounds/075.mp3'),
        require('./assets/sounds/076.mp3'),
        require('./assets/sounds/077.mp3'),
        require('./assets/sounds/078.mp3'),
        require('./assets/sounds/079.mp3'),
        require('./assets/sounds/080.mp3'),
        require('./assets/sounds/081.mp3'),
        require('./assets/sounds/082.mp3'),
        require('./assets/sounds/083.mp3'),
        require('./assets/sounds/084.mp3'),
        require('./assets/sounds/085.mp3'),
        require('./assets/sounds/086.mp3'),
        require('./assets/sounds/087.mp3'),
        require('./assets/sounds/088.mp3'),
        require('./assets/sounds/089.mp3'),
        require('./assets/sounds/090.mp3'),
        require('./assets/sounds/091.mp3'),
        require('./assets/sounds/092.mp3'),
        require('./assets/sounds/093.mp3'),
        require('./assets/sounds/094.mp3'),
        require('./assets/sounds/095.mp3'),
        require('./assets/sounds/096.mp3'),
        require('./assets/sounds/097.mp3'),
        require('./assets/sounds/098.mp3'),
        require('./assets/sounds/099.mp3'),
    ];

    return sound;
}